openapi: "3.0.0"
info:
  version: 0.0.1
  title: Go-Fast CDN
  description: A simple and fast CDN written in Go
  contact:
    name: Kevin Alex Nielsen
    email: kevinanielsen@outlook.com
    url: http://github.com/kevinanielsen/go-fast-cdn
  license:
    name: License Name
    url: http://example.com/license-url
paths:
  /download/:fileName:
    get:
      description: |
        Retrieve the file you want to access from the CDN.
      operationId: Receive Image
      parameters:
        - name: fileName
          in: query
          description: The name of the file you want to access.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: You have recieved the requested content from the CDN.
        "304":
          description: Redirect to the requested content.
  /api/cdn/upload/image/:
    post:
      description: |
        Upload image to CDN
      operationId: Upload Image
      requestBody:
        formData:
          - name: image
            description: The file of the image you want to upload
            required: true
            schema:
              type: image/jpeg, image/jpg, image/png, image/gif, image/webp, image/bmp
      responses:
        "200":
          description: You have successfully uploaded the image.
          content:
            application/json:
              schema:
                type: object
                properties:
                  file_url:
                    type: string
                    description: The URL of the uploaded image.
        "400":
          description: Invalid file-type or lack of file in formData.
          summary: Bad Request
